name: CustomRecipeAPI
version: 1.5.2
main: me.darkolythe.customrecipeapi.CustomRecipeAPI
api-version: 1.13

commands:
  crapi:
    usage: /<command>
    aliases: [customrecipeapi]
    description: the CRAPI command
    permission: crapi.command
    permission-message: You do not have permission!

permissions:
  crapi.command:
    description: Allows the use of CRAPI commands
    default: op
  crapi.book:
    description: Allows the use of the CRAPI recipe book
    default: op
  crapi.giveitem:
    description: Allows the use of the CRAPI recipe book to give items
    default: op
  crapi.new:
    description: Lets the user create new recipes in-game
    default: op
  crapi.setworkbench:
    description: Allows the user to update the workbench recipe
    default: op
  crapi.viewworkbench:
    description: Allows the user to view the workbench recipe
    default: op
  crapi.craft:
    description: Allows the user to craft custom recipes
    default: true
  crapi.craftall:
    description: Allows the user to craft every custom recipe
    default: op
  crapi.op:
    description: Allows the user to view the permission name of each recipe
    default: op